language: python
sudo: false
python:
  - "2.7"
  - "3.4"
  - "3.5"
env:
  - DJANGO=1.7
  - DJANGO=1.8
install:
  - pip install -q --upgrade pip
  - pip install -q Django==$DJANGO
  - pip install -q django-discover-runner
  - pip install -q mock
  - pip install coveralls
script:
  - coverage run --source=. run_tests.py
after_success:
  - coveralls
